- name: Web Restart Old Way
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: restarted
  listen: "restart nginx"

- name: Web Restart New Way
  service:
    name=nginx
    state=restarted
  listen: "restart nginx new"
